<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
	  <ApplicationIcon>Assets\sanigear-icon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\meow.mp3" />
    <None Remove="Assets\sanigear-logo.png" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Commands\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.2" />
    <PackageReference Include="Velopack" Version="0.0.1298" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="Assets\meow.mp3">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </Content>
    <Resource Include="Assets\sanigear-icon.ico" />
    <Resource Include="Assets\sanigear-logo.png">
      <CopyToOutputDirectory>Never</CopyToOutputDirectory>
    </Resource>
  </ItemGroup>

</Project>
